### ISSUE TITLE
loved your wrapper <3

### ISSUE THREAD

**Issue by voltuer** [tax/pywhatsapp#1]
Hi, it opened my mind about how the heck to use yowsup, but how could i read sent messages? any way to make it a daemon that acts on receive events? ty

**Comment by tax** [comment]
Hi @sebcl glad you liked it :smiley: . Regarding receiving messages: good question. This is currently not possible with this wrapper. 

I think the echo client might give you a direction:
https://github.com/tgalal/yowsup/tree/ead19236de67f50e3e241596f15765dbc8ece6e0/yowsup/demos/echoclient
and
https://github.com/tgalal/yowsup/blob/ead19236de67f50e3e241596f15765dbc8ece6e0/yowsup-cli#L257
