### ISSUE TITLE
pip failed 

### ISSUE THREAD

**Issue by AShabana** [tax/pywhatsapp#2]
pip install pywhatsapp  
File "/tmp/pip-build-Mv1Jyf/pillow/setup.py", line 515, in build_extensions
        % (f, f))
    ValueError: --enable-jpeg requested but jpeg not found, aborting.

**Comment by tax** [comment]
hi Ashabana 

What is your OS and what python version are you using?

**Comment by AShabana** [comment]
CentOS 7 . I able to resolve it by installing lib jpeg development package
