### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CURRENT_ENV'

### ISSUE THREAD

**Issue by syedair** [tax/pywhatsapp#4]
Hi,

I am getting the below error when I try to use this. 

Note, I have already successfully registered the client before this.

> > > from whatsapp import Client
> > > phone_to  = '<hidden>'
> > > client = Client(login='<hidden>',password='<hidden>')
> > > client.send_message(phone_to, 'Hello')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/whatsapp.py", line 152, in send_message
> > >     self._send_message(to, message)
> > >   File "/usr/local/lib/python2.7/dist-packages/whatsapp.py", line 142, in _send_message
> > >     self.stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())
> > > AttributeError: 'module' object has no attribute 'CURRENT_ENV'

**Comment by marcowork** [comment]
same here.

seems like the yowsup library is updated but not this repo. please change it.

It should be like this.
self.stack.setProp(YowCoderLayer.PROP_RESOURCE,env.YowsupEnv.getCurrent().getResource())

**Comment by tax** [comment]
This should be fixed with version 0.0.7 (which uses @marcowork fix and yowsup version 2.5.0) again thanks for the fix.
