### ISSUE TITLE
Message with newline?

### ISSUE THREAD

**Issue by ftbarata** [tax/pywhatsapp#6]
Hi Paul, I am looking for the syntax of sending messages with the newline (the carriage return equivalent) in yowsup2. Do you know how to do it?

**Comment by dargmuesli** [comment]
Have you tried simply including "\n" in your message string?

**Comment by ftbarata** [comment]
Hi @Dargmuesli thanks, I already found the right way. Putting the \n was not working because I was using '\n' instead of "\n".  Thanks for response.
My main problem now is this:  https://github.com/tgalal/yowsup/issues/1305#issuecomment-243695724

Do you have any experience with this?

**Comment by dargmuesli** [comment]
No, unfortunately I cannot help you there as I'm using yowsup myself since yesterday only :D
But I'll try to get the rough idea of its usage in the next days and maybe I'll be able to help you then. But for me it's difficult to understand too, so I can't promise you anything here... :/

**Comment by ftbarata** [comment]
It's ok! Many thanks!

**Comment by dargmuesli** [comment]
I'll email you if I find anything interesting. For now, you can close this issue i think. :)
